# Generated by Django 3.0.5 on 2020-05-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='LastName', max_length=255),
            preserve_default=False,
        ),
    ]
